name: generate map

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  updateeventmap:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 #install the python needed
      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto event update"
          git push
        env:
          auth_url: ${{ secrets.AUTH_URL }}
          activities_url: ${{ secrets.ACTIVITIES_URL }}
          payload: |
            {
                "client_id": "${{ secrets.CLIENT_ID }}",
                "client_secret": "${{ secrets.CLIENT_SECRET }}",
                "refresh_token": "${{ secrets.REFRESH_TOKEN }}",
                "grant_type": "refresh_token",
                "f": "json",
            }
